# Generated by Django 4.0.4 on 2023-10-04 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_answer_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifier', to='chat.leader'),
        ),
    ]
