# Generated by Django 4.0.4 on 2023-10-02 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_credential', models.CharField(max_length=75)),
                ('bio', models.CharField(max_length=75)),
                ('user_pr', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=75)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField(blank=True, null=True)),
                ('currently_live_here', models.BooleanField()),
                ('user_lo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_lo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=75)),
                ('company_organization', models.CharField(max_length=75)),
                ('start_year', models.DateField(default='2020-02-04')),
                ('end_year', models.DateField(blank=True, null=True)),
                ('currently_work_here', models.BooleanField()),
                ('user_em', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_em', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_major', models.CharField(max_length=75)),
                ('secondary_major', models.CharField(max_length=75)),
                ('degree_type', models.CharField(max_length=75)),
                ('user_ed', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
